### ISSUE TITLE
probles in platform i386-w64-mingw32/i386 (32-bit)

### ISSUE THREAD

**Issue by manel01** [melff/memisc#12]
While testing memisc I got a strange problem. It works well in platform x86_64-w64-mingw32/x64 (64-bit) but not in platform i386-w64-mingw32/i386 (32-bit).

It's a bug or I missed something?

Thanks,

Manel Salamero
manelsalamero@gmail.com

PS: I attached a file with the instructions and results.
[memisc_test.txt](https://github.com/melff/memisc/files/372302/memisc_test.txt)

**Comment by melff** [comment]
I cannot see any difference between your 32bit and 64bit output. The error message that you receive does not indicate a bug. The reason is simply that the `wild.codes()` generic function has a method only for "item" objects. A method for "data.set" objects may be implemented in future updates.

**Comment by manel01** [comment]
Thalks for your comment.

Manel Salamero

2016-08-16 10:59 GMT+02:00 Martin Elff <notifications@github.com>:

**Comment by attia5** [comment]
The Same Problem here
