### ISSUE TITLE
How do I dynamically use subset selections

### ISSUE THREAD

**Issue by paulb20** [melff/memisc#13]
My use case is that I'm using the UK Labour Force Survey, and I want to pool a number of datasets. 

I only want to load a small number of variables for analysis, but the variable names change between datasets depending on the naming convention. The weight variable changes from time to time (pwt16, pwt14, pwt11 etc). 

I'd like to load a list of datasets, do a set of transformations to common form, and then pool the datasets for analysis using the survey or svryr packages.

When I try to use the subset specification as a pre-prepared character vector, I get 
Error in max(sapply(args, length)) : invalid 'type' (list) of argument.

**Comment by melff** [comment]
Sorry, but this is not a package issue but a support request. Further, I cannot solve your problem without example code and example output.
