### ISSUE TITLE
Forum / Mailinglist

### ISSUE THREAD

**Issue by buhtz** [melff/memisc#17]
There should be a forum or a mailinglist related to `memisc`.

Currently I see no good way to ask `memisc`-related questions. GitHub-issuses are for development bug-reports etc and not for support questions.
StackOverflow doesn't over a `memisc` tag currently.

This is the currently opened question http://stackoverflow.com/questions/41208734/how-to-drop-labels-from-a-memiscdata-set-in-r.

**Comment by melff** [comment]
I am doing this in my free time. Occasionally I get support questions via memisc@elff.eu, which I usually answer. Since I do not now how widespread the use of the software I am not sure whether it is worthwhile setting up a mailing list. (I would also have to moderate it to keep the spam away etc.)

**Comment by buhtz** [comment]
IMO your arguments doesn't fit together.
You recieve support questions via your private e-mail. This is a private channel. Only you can read and answer. No one else is able to help. And the worst thing is that the solutions not documented for all users.

A Forum, Mailinglist or whatever is a public channel. You can read but you don't have to. Other users can read and search for old questions/answers fitting to their own questions.

This would save a lot of ressources for yourself when using a public support channel. Then you have more "free time".

I would recommend you to use stackoverflow. There it is possible to keep you automaticly informed about new questions with "memisc" in title or as a tag.
