### ISSUE TITLE
mysteric behaviour with factors and labels

### ISSUE THREAD

**Issue by buhtz** [melff/memisc#18]
Please see this basi-R example with a `data.frame`.

```
d <- data.frame(a = sample(1:100))
d$a_strat <- cut(d$a, breaks=seq(1,100, by=10)) # stratify by 10
e <- d[,c('a_strat')]

> str(d$a_strat)
 Factor w/ 9 levels "(1,11]","(11,21]",..: 2 6 1 8 6 9 5 3 NA 9 ...
> str(e)
 Factor w/ 9 levels "(1,11]","(11,21]",..: 2 6 1 8 6 9 5 3 NA 9 ...
```

You see the labels for levels ar not lost. But when I do the same with a `memisc:data.set` they are lost.

```
d <- data.set(a = sample(1:100))
d$a_strat <- cut(d$a, breaks=seq(1,100, by=10))
e <- d[,c('a_strat')]

> str(d$a_strat)
 Factor w/ 9 levels "(1,11]","(11,21]",..: 4 9 3 1 NA 9 5 4 9 9 ...
> str(e)
Data set with 100 obs. of 1 variable:
 $ a_strat: Nmnl. item w/ 9 labels for 1,2,3,...  int  4 9 3 1 NA 9 5 4 9 9 ...
```

What is behind that behaviour?

**Comment by melff** [comment]
The labels are not lost, they simply do not show up individually in the output `str()`, which just summarily reports that there are 9 labels present. You can see the labels with `codebook(e)`.

**Comment by buhtz** [comment]
That doesn't fix the problem. Please re-open and don't close a feauter before the opener told it is fixed. It is unpolite and wasting ressources.

The point is I need to use the labels for the ticks in some plots.

I can do this on the original 'data.set`.

```
> levels(d$a_strat)
[1] "(1,11]"  "(11,21]" "(21,31]" "(31,41]" "(41,51]" "(51,61]" "(61,71]"
[8] "(71,81]" "(81,91]"

```

But I can not do this

```
> levels(e)
NULL

```

You are right, I see kind of lables in the output of `codebook()`. But I can I get them as a list?

**Comment by melff** [comment]
GitHub's issue reporting infrastructure is for bug reports not for support questions, therefore it is not impolite to close an issue that is a support question. Please respect that offering R-packages is _voluntary work_ and does not oblige anyone to offer support. Before you file issues, please make sure that you have read and understand the documentation of the package - there is a difference between factors and the item objects present in `data.set`s.
