### ISSUE TITLE
importing large files

### ISSUE THREAD

**Issue by paynito** [melff/memisc#19]
Hi, I get an out of memory error

    > dataset2003<- as.data.set(spss.portable.file("../rawData/census/f463/f463ind.por"))
    Error in readStringPorStream(pstream) : 
     cannot allocate memory block of size 16777216 Tb

Is there any way around this?  I want to import 15 files of this size and can't even do 1.

**Comment by melff** [comment]
Have you tried 'subset()'?

What version of memisc are you using?

How large are the files you want to import?

**Comment by paynito** [comment]
memisc v.0.99.8,   files are from 1 to 25 MB each, will try subset(), thanks for the fast reply.

**Comment by melff** [comment]
Hmm those files are not large - maybe you've found a bug. Is it possible to 
get an example data file? Thanks.

**Comment by paynito** [comment]
I think it was a problem with my "individual" file.  The family file imports great.  Thank you for this package. Closing issue. 
    
    ZZTop <- spss.portable.file("../rawData/census/f463/f463fam.por")
