### ISSUE TITLE
SPSS variable names trimmed by memisc/spss.system.file?

### ISSUE THREAD

**Issue by Mike-Todd** [melff/memisc#2]
Hi Martin:

In my experience so far, It seems as though variable names exceeding 8 characters are trimmed to 8 characters when importing from SPSS .sav files to R. Any subsequent variable names sharing the same initial 8 characters are subsequently coerced into unique, but generic, strings (e.g., longername1 -> longerna, longername2 -> V2_a, longername3 -> V3_a).  

I'm wondering if perhaps there is something I'm overlooking or doing incorrectly, as I've seen no mention of variable name truncation in the documentation or any of the discussions I've read. I did go as far as to read the pspp-system-for-R.c code where I saw the following call in line 412: trim(curr_var.name,8). I don't know if this bit of code is relevant to my query, but it did make me wonder if the truncation of variable names was by design and static (i.e., there is no option to turn it off). 

If it is not an intentional feature, would you have any ideas about why my variable names are being trimmed? If this, however, is a feature, would altering it be a possibility in the future? 

Thanks!

-Mike

**Comment by melff** [comment]
Hi Mike,

line 412: `trim(curr_var.name,8)` is for trimming variable names that are *shorter* then 8 letters long. Traditionally SPSS supported variable names only up to 8 letters length. Newer SPSS files contain auxiliary information that maps long variable names to traditional 8-letter names and this auxiliary information is handled by some other code. So `memisc` should be able to handle long variable names (in my test cases it did so). 

There might be two reasons for your problems - for some reasons this long variable name information somehow was not in the SPSS file, or SPSS have changed their file format. 

Can I ask you to send me some example data that I can use for debugging?

Thanks,
Martin

**Comment by Mike-Todd** [comment]
Hi Martin:

My apologies. The problem appears to have been connected to the outdated version of R that I was using (3.1.2). I've been dividing my work across two computers lately, and I didn't realize that one of the machines was lagging behind in terms of software updates. After updating to version 3.2.1, everything worked as expected. Thanks for the quick response and your willingness to diagnose the (non-)issue!
