### ISSUE TITLE
parseHeaderPorStream(ptr) : unknown tag "T" found

### ISSUE THREAD

**Issue by paynito** [melff/memisc#20]
Is there anyway to work past such an error?

    m2003 <- spss.portable.file("../rawData/census/f466/f466ind.por")
    [1] "f basic metalS/21/Manufacture of metal products (excl. machinery and equipment)T"
    [2] "/18/Manufacture of machinery and equipment10/20/Manufacture of office and accoun"
    Hide Traceback
    Error in parseHeaderPorStream(ptr) : unknown tag "T" found in line 65 offset 54
    stop("unknown tag ", dQuote(tag.code), " found in line ", currline, " offset ", offset)
     parseHeaderPorStream(ptr)

**Comment by paynito** [comment]
File imports fine when I switch to 

    library(Hmisc)
    m2003 <- spss.get("../rawData/census/f466/f466ind.por",
                  use.value.labels = TRUE)

**Comment by melff** [comment]
Thanks for reporting the bug. It is fixed in release [0.99.9.1](http://github.com/melff/memisc/releases/tag/0.99.9.1).
