### ISSUE TITLE
relabel with gsub 

### ISSUE THREAD

**Issue by hpykala** [melff/memisc#21]
I'm having issues with relabeling items using argument gsub = TRUE. The regular expression produces incorrect matches. For example trying to relabel c to foo by regular expression also relabels a, which should not be matched by c at all:

`f <- as.factor(rep(letters[1:4],5))`
`f <- as.item(f)`
`f2 <- relabel(f, c = 'foo', gsub = TRUE)`
`labels(f)`
 Values and labels:

   1 'a'
   2 'b'
   3 'c'
   4 'd'

`labels(f2)`

 Values and labels:

   1 'foo'
   2 'b'  
   3 'foo'
   4 'd'  

I expected following result:

 Values and labels:

   1 'a'  
   2 'b'  
   3 'foo'
   4 'd'

**Comment by melff** [comment]
Thanks for reporting the bug. It is fixed in release [0.99.9.1](http://github.com/melff/memisc/releases/tag/0.99.9.1).
