### ISSUE TITLE
Reduce output content of codebook()?

### ISSUE THREAD

**Issue by d4ff** [melff/memisc#22]
Hi, great package, love your work.

I'm wondering if there is any straight-forward way of manipulating content from codebook(). It's producing more output than I want in my documentation.

How do you suggest getting codebook() output without information on the following objects:
-storage mode & measurement
-description
-N and percent

Thanks <3

**Comment by melff** [comment]
D4ff, thanks for your feedback.

The information you mention is the amount of information that social scientists usually require of a published survey data set. Without it a codebook would be almost empty. I wonder for what purposes do you need `codebook()` anyway? If there is "popular demand" for such a set of information I would implement the appropriate function in R. 

On the other hand, I suppose that the output of `codebook()` is sufficiently regular to allow for some post processing by a Ruby or Python script.

**Comment by d4ff** [comment]
Thank you for the quick response.

I'm developing a script that automatically produces a 'questionnaire' document to accompany survey datasets. The data is based on websurveys, so all of the information is already available in a machine-readable format, I'm importing it to R via SPSS files that I download directly from the websurvey platform. The idea is that a script produces the documentation based on the datafile, eliminating any potential for human-error and inconsistencies between the two. It also allows me to produce the same style of data / documentation at any point during the websurveys life cycle with minimum effort.

The purpose of this documentation is to simply inform the user about the contents of a dataset without the need to look at it through a statistical software package. The information included in the [ESS Questionnaires](http://www.europeansocialsurvey.org/docs/round7/fieldwork/source/ESS7_source_main_questionnaire.pdf) is a good example of what I mean, but I really like how memisc allows me to add additional information about each variable in codebook() through annotation(), so I want to incorporate this into the script.

While I agree that the codebook function contains useful information, I think it's a bit 'too much information' for the documentation outlined above. I'm thinking that instead of altering the codebook function, I should build on it with a python script, and use LaTeX to get the final documents that I want.

Any input / tips would be greatly appreciated. And again, thank you for developing memisc, it has been tremendously helpful.

**Comment by DiogoFerrari** [comment]
Here is a suggestion using tibble (you need [tidyverse](https://www.tidyverse.org/) and [magrittr](https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html) :

```
get.cb <- function(x)
{
    options(warn=-1)
    on.exit(options(warn=0))
    ## Debug/Monitoring message --------------------------
    msg <- paste0('\n','Creating codebook ...',  '\n'); cat(msg)
    ## ---------------------------------------------------
    tab = memisc::codebook(x) %>% 
        tibble::data_frame(var      = names(.),
                           desc     = purrr::map_chr(.x=.@.Data, function(.x) .x@annotation@.Data) %>% stringr::str_trim(.),
                           coding = .@.Data) %>%
        dplyr::mutate(coding = purrr::map(.x=coding, function(.x) get.cb.labels(.x)) ) %>%
        dplyr::select(var, desc, coding) 
    return(tab)
}

```

**Comment by melff** [comment]
Since release [0.99.16](https://github.com/melff/memisc/releases/tag/0.99.16) there is a function `codeplan()` which produces a data frame with information about variable labels, value labels, etc. It should be easy to select rows and columns from such a data frame. Is this something you were thinking of?
