### ISSUE TITLE
Problems with slicing: "read_sysfile_slice" not resolved from current namespace

### ISSUE THREAD

**Issue by jwigit** [melff/memisc#28]
Hi,

I have been processing SPSS .sav files with great success with an older version of memisc and R on Windows.

I have recently upgraded to the 3.4 series of R and memisc version 0.99.14.2.

In code where I use slicing e.g.:
`data_sp[,2]`
or
`data_sp[,names(data_sp)=="grp"]`
I now get this error:
`Error in .Call("read_sysfile_slice", x@ptr, what = x, j = cols, i = rows,  :
  "read_sysfile_slice" not resolved from current namespace (memisc
`

I find the function "read_sysfile_slice" in pspp-system-for-R.c.

I believe that "read_sysfile_slice" should be exported in memisc.h

Best regards,

Jon Wickmann

**Comment by melff** [comment]
This seems to be fixed with release 0.99.14.3, [which can be installed from GitHub](https://github.com/melff/memisc/releases/tag/0.99.14.3) and is hopefully available soon on CRAN.
