### ISSUE TITLE
to.data.frame not working

### ISSUE THREAD

**Issue by DiogoFerrari** [melff/memisc#32]
I am trying to convert a data set to data.frame using to.data.frame, after loading it using memisc::spss.system.file(filename) and subset(..). I get the following error:

+ Error in as.factor(x) : Duplicate labels

**Comment by melff** [comment]
I guess you mean `as.data.frame`? Anyway - what you see is not a bug in the package but in the data: Some of your variables seem to have duplicated value labels.
