### ISSUE TITLE
Using string variable with variable names to subset .sav data

### ISSUE THREAD

**Issue by DiogoFerrari** [melff/memisc#35]
The function `memisc::subset()` does not allow us to use string variable as parameter for select. Currently, you can't do:

```
sav <- memisc::spss.system.file(filename) 
vars = c("var1", "var2")
data =  memisc::subset(sav, select=vars)
```

That simple limitation is a little counterproductive and makes the package less portable. I am proposing a  modification in the file `importer-methods.R` below, in the  function `setMethod("subset","importer",...`. The modification preserves the current way the subset works, but now also accepts a string vector in the select parameter of the function subset in the package. I posted it here instead or using a pull request because this little piece of code is sufficient to do the job.

CURRENT CODE:

```
setMethod("subset","importer", 
    function (x, subset, select, drop = FALSE,
              ...)
....
        nl <- as.list(1:nvars)
        names(nl) <- names
        cols <- logical(nvars)
        cols[eval(substitute(select), nl, parent.frame())] <- TRUE
        select.vars <- sapply(substitute(select)[-1],as.character)
....
{
```

PROPOSED MODIFICATION:

```
setMethod("subset","importer", 
    function (x, subset, select, drop = FALSE,
              ...)
....
        nl <- as.list(1:nvars)
        names(nl) <- names
        cols <- logical(nvars)
        if (class(substitute(select)) == 'call') {
            cols[eval(substitute(select), nl, parent.frame())] <- TRUE
            select.vars <- sapply(substitute(select)[-1],as.character)
        }else{
            select.vars = select
            cols[which(names(nl) %in% select.vars )] = TRUE
        }
....
{
```

**Comment by melff** [comment]
Thanks! I included this in release [0.99.16.1](https://github.com/melff/memisc/releases/tag/0.99.16.1).
