### ISSUE TITLE
Removing digits when using `toLatex` directly with `ftable`

### ISSUE THREAD

**Issue by InazeaAnazasi** [melff/memisc#37]
For some very simple tables (with only one variable, counting the number of appearances of that variable), I use xtabs to generate the table and then export it with `ftable`. However, doing so adds no less than seven decimal digits.
What could be the reason for this? How could the decimal digits be made to disappear in the finale, LaTeX-ready table (without manually removing them in the .tex-file)?

**Comment by melff** [comment]
See the `digits=` and `ddigits=` options in `?toLatex`.

Please note that the issues system in GitHub is for bug reports and feature requests, but not basic support questions.
