### ISSUE TITLE
Processing SPSS control files

### ISSUE THREAD

**Issue by jciconsult** [melff/memisc#38]
Having double quotes embedded in a quote string does not work.  In other words, this string
"Has used drugs - lifetime (incl marijuana ""just once"")"
                    2   
does not work.  I had to replace the double quotes with the ` character to read the file.
[SPSS.zip](https://github.com/melff/memisc/files/2751045/SPSS.zip) are the examples.
I can provide a link to the data file if you wish to test it but it is 18mb zipped

**Comment by melff** [comment]
Fixed with 9f9650b
