### ISSUE TITLE
Variables with duplicate labels cause an infinite loop in xtabs

### ISSUE THREAD

**Issue by jciconsult** [melff/memisc#39]
The Statcan SPSS file that I am processing (community health survey) has two variables with duplicate labels.  If these variables are in the dataset that is used a source for xtabs, even if the variables are not in the xtab, there is an error message about factor problems and R hangs in a loop).

**Comment by melff** [comment]
Have you tried running this with the most recent release on Github? Anyway, without example data, I am unable to identify and fix the but that may cause this issue.

**Comment by jciconsult** [comment]
The new code does not cause a problembin the machine at my farm. I am going
to update all my machines. I am back in Toronto and have not done that here
but will confirm before and after results. Could you please identify the
function that gives me the name of variables with duplicate lists. Thanks
in advance.

from Paul Jacobson's mobile device

**Comment by melff** [comment]
?duplicated_labels
