### ISSUE TITLE
summary.stats.default is unused

### ISSUE THREAD

**Issue by bastistician** [melff/memisc#41]
Extending mtable for a new model class "cls" currently requires specifying a corresponding "summary.stats.cls" option in addition to a `getSummary.cls` method, otherwise no summary statistics are displayed with the default `summary.stats = TRUE` argument of `mtable()`. From what `help("mtable")` says about `summary.stats`, I would have expected that all summary statistics from `getSummary.cls()` are reported when no such option has been defined.

A minimal reproducible example follows:

```R
lm0 <- lm(sr ~ pop15 + pop75, data = LifeCycleSavings)
class(lm0) <- "cls"
getSummary.cls <- function (obj, ...) {
    class(obj) <- "lm"
    getSummary.lm(obj, ...)
}
mtable(lm0, summary.stats = TRUE)  # summary statistics are not shown
mtable(lm0, summary.stats = "N")   # works
oopt <- options("summary.stats.cls" = getOption("summary.stats.default"))
mtable(lm0, summary.stats = TRUE)  # now the defaults (logLik and N) are shown
options(oopt)
```

The reason is that "summary.stats.default" will not be selected in `selectSummaryStats`:

https://github.com/melff/memisc/blob/977c0227ebcca993875652925f730f14b63a9240/pkg/R/mtable.R#L85-L93

The condition `length(sumstats)` equals the length of the class vector `class(x)`, which will contain at least one element for a new model class, so the option "summary.stats.default" won't come into play and "summary.stats.cls" needs to be specified to avoid a NULL result.

Should the condition be replaced by something like `any(!vapply(sumstats, is.null, TRUE))`?

**Comment by melff** [comment]
Thanks! This is fixed (hopefully) by commits  859c860..9807310.
