### ISSUE TITLE
Exhibit odds ration in the regression estimates table [question]

### ISSUE THREAD

**Issue by gustavobrp** [melff/memisc#46]
Hello,

A question related to the `memisc `package. Is it possible to present the exponentiated coefficients of a GLM model? I used the `mtable()` function to exhibt the results from a model from the `mclogit() `and `lme4()` package, and tried to see if there was an option to report the estimates as odds ratio.

Thanks you very much.

**Comment by melff** [comment]
If you call `mtable()` with optional argument `getSummary=getSummary_expcoef` using the current memisc version eeb9731e9b1ee4a40aefe61cece8999d8d9afe6d, it should be possible to get exponentiated coefficents.

**Comment by gustavobrp** [comment]
Hi Martin,

Just tested and it worked perfectly. 

Thanks a lot.
