### ISSUE TITLE
Suggestion for new method codebookEntry

### ISSUE THREAD

**Issue by r-re** [melff/memisc#5]
memisc appears to be lacking a dedicated codebookEntry for the "dateitem.item " class, instead defaulting to "atomic" which uses the R's "summary" method. Because this function does not provide information on [missing values](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=14720), codebookEntry appears to be missing information on missings in date-Variables as well.

Here is some quick code, i used to patch this after the package is loaded. It's not perfect but it seems to provide the needed information.

```
# set the method after loading the package
setGeneric("codebookEntry", getGeneric("codebookEntry", package="memisc"))
```

```r
setMethod("codebookEntry","datetime.item",function(x){
  spec <- c(
    "Storage mode:"=storage.mode(x)
  )
  isna <- is.na(x)
  stats <- summary(x)
 stats <- list(descr=cbind(names(stats),paste(stats), NAs=sum(isna)))
  new("codebookEntry",
      spec = spec,
      stats = stats,
      annotation = annotation(x)
  )
})
```

What do you think?

**Comment by melff** [comment]
Thanks for pointing me to the bug the regarding the `codebookEntry` method for the "datetime.item" class. The method existed actually, but did not report the number of missing values. This is now fixed with the last commit. The trick actually is:
```r
setMethod("codebookEntry","datetime.item",function(x){
  annotation <- annotation(x)
  filter <- x@value.filter
  spec <- c(
            "Storage mode:"=storage.mode(x),
            "Measurement:"="Date/time"
            )
  if(length(filter)) spec <- c(spec,
                              switch(class(filter),
                                        missing.values = c("Missing values:" = format(filter)),
                                        valid.values   = c("Valid values:"   = format(filter)),
                                        valid.range    = c("Valid range:"    = format(filter))
                                        ))
  ism <- is.missing(x)
  isna <- is.na(x)
  new("codebookEntry",
    spec = spec,
    stats = list(
      descr=format(c(
                     format(summary(x)),
                    `N.miss.` = sum(ism & !isna),
                    NAs = sum(isna)),
                    justify="left")
      ),
    annotation = annotation
  )
})
```

**Comment by r-re** [comment]
Works like a charm. Thanks for the quick response

**Comment by melff** [comment]
Note that this is in the current release of memisc (0.99.4) now.
