### ISSUE TITLE
Error when generating codebook

### ISSUE THREAD

**Issue by systemnova** [melff/memisc#50]
When importing with the following syntax, description works but i get an error generating the codebook.
  ZA <- spss.system.file(Alt_in)
  description(ZA)
  codebook(ZA)

The error generated says:
"Error in if (ncol(descr) > 1) { : argument is of length zero"

If i ask for a codebook on a specific variable, it works.
I'm sure it's something simple I'm missing?

**Comment by melff** [comment]
That is a bug that I noticed as well. It is going to be fixed (hopefully) by the upcoming release.

**Comment by systemnova** [comment]
I just updated to the latest github release and it seem to now be working.
Can i also just say a big thank you for this library! Super appreciative of all your hard work & smarts!

**Comment by melff** [comment]
Thanks for the kind words. This is what keeps me going (apart from the fact that the package is useful mostly for me :).

**Comment by systemnova** [comment]
Not sure if related, but when i go to use wild.codes it generates the following error:

>     memisc::wild.codes(ZA)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘wild.codes’ for signature ‘"spss.system.importer"’

**Comment by melff** [comment]
Thanks. I'll fix that before the next release (coming soon).

**Comment by systemnova** [comment]
I was applying to a dataframe instead of variable. No more error code.

**Comment by systemnova** [comment]
ME_DF <- as.data.frame(ZA)

Produces the error:
Error in as.ordered(x) : Duplicate labels

**Comment by melff** [comment]
This may be caused by `ZA` having variables with duplicate labels. *memisc* has a function `deduplicate_labels()` for dealing with this.
