### ISSUE TITLE
unable to read spss

### ISSUE THREAD

**Issue by vgeo999** [melff/memisc#55]
Hi there, 
for five years I am using memisc in my standard projects but only recently my script stopped working. I have no clue, whether it was a Microsoft update or R update or maybe even memisc update, but every time I try to read in SPSS files into R using `spss.file()` or `spss.system.file()` I only get the error: 

> Error in sprintf("File character set is '%s'.", encoding) : 
  object 'encoding' not found

For some reason, I have no problem reading the same SPSS file with `read.spss()` from foreign package, but since I am using other functionality from memisc as well, I don't want to use foreign but rather use my previous script. So far, I am unable to even start my workflow and cannot figure out why. Do you have any idea or suggestion?

Thank you very much and greetings from germany
Liz

**Comment by melff** [comment]
That is definitly a bug. It appears to have been created by changes made in May last year. You will shall find a fix in the next Git commit.
