### ISSUE TITLE
spss.fixed.file() dropping final observation

### ISSUE THREAD

**Issue by rkurdyak** [melff/memisc#57]
Hi,

I am working with a dataset similar to a Statistics Canada PUMF file (I think it was #44 that had a similar layout), and I am noticing that when I import a dataset using spss.fixed.file(), it omits the last observation in the survey. Is this a normal feature, or is there some way around this? One observation isn't a huge deal, but I would really like to include it.

Thanks!

**Comment by melff** [comment]
Dropping the last observation is of course not intended. I consider this a bug which I'll fix ASAP. 

Thanks for reporting!

**Comment by rkurdyak** [comment]
Hi again,

Between now and then, I was wondering if you have any suggestions for reliably importing SAS, STATA, or SPSS files of a similar format (i.e., .txt file with associated SAS, SPSS, or STATA files). If there's any other coverage in your package that works, I'd be more than happy to use it!

Thanks

**Comment by melff** [comment]
The reported bug should be fixed by the recent commit https://github.com/melff/memisc/commit/0565eda3b1072f1f8fb6b2731e3f996826580545. Can you check please? (It seems fixed on my machine).

**Comment by rkurdyak** [comment]
Thank you for doing this! It appears to be fixed on my system as well! Would this become updated? I just have some security issues, and probably wouldn't be able to work on it anywhere other than my personal computer.
