### ISSUE TITLE
Can you send me /memisc.0.99.22?

### ISSUE THREAD

**Issue by bixiou** [melff/memisc#61]
Hi,
for some reasons, I need the version 0.99.22 of memisc, on Windows. 
Using `install_version("memisc", version = "0.99.22", repos = "http://cran.us.r-project.org", upgrade = "never", dependencies = TRUE)` doesn't work, it enters an infinite loop of dependency installations. 
My usual workaround is to copy/paste an already compiled /memisc folder in my R library and install it from the binaries: `install.packages("memisc", method = "win.binary")``
Unfortunately, as I changed computers, I forgot to save the precious /memisc folder. 
I am wondering if a generous soul could send me this folder (for the 0.99.22 version compiled on Windows). Or explain me how to install it without bug.

**Comment by melff** [comment]
Maybe try https://github.com/melff/memisc/releases/tag/0.99.22 ?

**Comment by bixiou** [comment]
Wonderful, with `install.packages("https://github.com/melff/memisc/releases/download/0.99.22/memisc_0.99.22.tar.gz", repos=NULL)` it worked! Thanks a lot <3
